.TH "draph::Link" 3 "Mon Apr 22 2019" "Version 0.1.0" "Draph" \" -*- nroff -*-
.ad l
.nh
.SH NAME
draph::Link
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "string \fBcreated_time\fP"
.br
.ti -1c
.RI "string \fBdescription\fP"
.br
.ti -1c
.RI "\fBUser\fP \fBfrom\fP"
.br
.ti -1c
.RI "string \fBicon\fP"
.br
.ti -1c
.RI "string \fBlink\fP"
.br
.ti -1c
.RI "string \fBmessage\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "string \fBpicture\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 17 of file draph\&.d\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Draph from the source code\&.
