.TH "event::event" 3 "Mon Apr 22 2019" "Version 0.1.0" "Draph" \" -*- nroff -*-
.ad l
.nh
.SH NAME
event::event
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBid\fP"
.br
.ti -1c
.RI "int \fBattending_count\fP"
.br
.ti -1c
.RI "bool \fBcan_guests_invite\fP"
.br
.ti -1c
.RI "string \fBcategory\fP"
.br
.ti -1c
.RI "CoverPhoto \fBcover\fP"
.br
.ti -1c
.RI "int \fBdeclined_count\fP"
.br
.ti -1c
.RI "string \fBdescription\fP"
.br
.ti -1c
.RI "bool \fBdiscount_code_enabled\fP"
.br
.ti -1c
.RI "string \fBend_time\fP"
.br
.ti -1c
.RI "ChildEvent [] \fBevent_times\fP"
.br
.ti -1c
.RI "bool \fBguest_list_enabled\fP"
.br
.ti -1c
.RI "int \fBinterested_count\fP"
.br
.ti -1c
.RI "bool \fBis_canceled\fP"
.br
.ti -1c
.RI "bool \fBis_draft\fP"
.br
.ti -1c
.RI "bool \fBis_page_owned\fP"
.br
.ti -1c
.RI "int \fBmaybe_count\fP"
.br
.ti -1c
.RI "string \fBname\fP"
.br
.ti -1c
.RI "int \fBnoreply_count\fP"
.br
.ti -1c
.RI "Group \fBparent_group\fP"
.br
.ti -1c
.RI "Place \fBplace\fP"
.br
.ti -1c
.RI "string \fBscheduled_publish_time\fP"
.br
.ti -1c
.RI "string \fBstart_time\fP"
.br
.ti -1c
.RI "string \fBticket_url\fP"
.br
.ti -1c
.RI "string \fBticket_uri_start_sales_time\fP"
.br
.ti -1c
.RI "string \fBticketing_privacy_uri\fP"
.br
.ti -1c
.RI "string \fBticketing_terms_uri\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file event\&.d\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Draph from the source code\&.
